[zh]
  languageName = "简体中文"
  contentDir = "content/zh"
  weight = 15
  [zh.params]
    languageISO = "ZH"
    languageTag = "zh-CN"
    footer = '由 <a class="text-muted" href="https://gethyas.com/">Hyas</a> 提供技术支持'
    alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Doks 1.0 版本已发布！</a>'
